name:                complib
version:             0.1.0.0
github:              "samvv/learn-type-inference"
license:             BSD2
author:
- Sam Vervaeck <samvv@pm.me>
- Megaparsec contributors
- Paolo Martini <paolo@nemail.it>
- Daan Leijen <daan@microsoft.com>
maintainer:          "Sam Vervaeck <samvv@pm.me>"
copyright:           "Copyright Sam Vervaeck 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Tools and utilities for writing fast compilers
category:            Compiler
description: >
  This is a package combining several other Haskell packages into one big
  optimised library for compiler development. Includes parser combinators and
  helper functions for building your own REPL.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - base >=4.13 && <5.0
  - bytestring >=0.2 && <0.12
  - case-insensitive >=1.2 && <1.3
  - containers >=0.5 && <0.7
  - deepseq >=1.3 && <1.5
  - mtl >=2.2.2 && <3.0
  - parser-combinators >=1.0 && <2.0
  - scientific >=0.3.1 && <0.4
  - text >=0.2 && <1.3
  - transformers >=0.4 && <0.6

tests:
  complib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - complib
    - scientific
    - hspec
    - QuickCheck
    - bytestring
    - text
    - containers
    - mtl
    - transformers
    - hspec-expectations
    - case-insensitive
