name:                optimising-hindley-milner
version:             0.1.0.0
github:              "samvv/learn-type-inference"
license:             BSD3
author:              "Sam Vervaeck"
maintainer:          "samvv@pm.me"
copyright:           "Copyright Sam Vervaeck 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/samvv/learn-type-inference#readme>

dependencies:
- base >= 4.7 && < 5
- eveff
- bytestring
- text
- toy

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - megaparsec
  - containers
  - parser-combinators

executables:
  main:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimising-hindley-milner
    - repline
    - mtl

tests:
  optimising-hindley-milner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimising-hindley-milner
    - hspec
    - QuickCheck

